#ifndef HAL_CONF_EXTRA_H
#define HAL_CONF_EXTRA_H

#define HAL_ADC_MODULE_DISABLED
#define HAL_CRC_MODULE_DISABLED
#define HAL_I2C_MODULE_DISABLED
#define HAL_I2S_MODULE_DISABLED
#define HAL_SPI_MODULE_DISABLED
#define HAL_CAN_MODULE_DISABLED

#endif